language: ruby

addons:
  chrome: stable

rvm:
  # The version used at CaaS Platform
  - 2.1.9

  # Other ruby versions
  - 2.2.7
  - 2.3.4
  - 2.4.1

  # Latest ruby
  - ruby-head

env:
  - RSPEC_FAIL_FAST=false LDAP_BIND_PASSWORD=Password1234 LDAP_PORT=3389 LDAP_HOST=localhost
# Used to get a better understanding of flaky tests. With a fail fast and a flaky test, the test.log
# file will probably contain relevant information to fix the problem.
#  - RSPEC_FAIL_FAST=true

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4.1

cache:
  bundler: true

before_install:
  # Install and setup chromium
  - sudo sh .ci/chromium-setup.sh


  # Use the latest stable Node.js
  - nvm install stable
  - nvm use stable

  # Install Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install yarn
  - yarn install

before_script:
  - mkdir /tmp/slapd
  - slapd -f travisci-slapd.conf -h ldap://localhost:3389 &
  - sleep 5
  - ldapadd -H ldap://localhost:3389 -D cn=admin,dc=infra,dc=caasp,dc=local -w Password1234 -f default.ldif
  - bundle exec rake db:setup

script:
  - yarn eslint
  - bundle exec rubocop -V
  - bundle exec rubocop
  - bundle exec brakeman -c config/brakeman.ignore -z -A
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: f6e3f94baf7a2d672fa17cd11deb8d3e0709be5350ad0dd11e33f44f54d540bd
  mariadb: '10.0'
  apt:
    packages:
    - ldap-utils
    - slapd
    - libmariadbclient-dev

after_success:
  - bundle exec codeclimate-test-reporter

after_failure:
  - cat log/test.log
